### PR TITLE
Significant dyn-abi fixes :)

### LINKED ISSUE #167: [Bug] Certain dynamic data fails to decode
### Component

dyn-abi

### What version of Alloy are you on?

├── alloy-dyn-abi v0.2.0 (https://github.com/alloy-rs/core?branch=main#3eab410e) │   ├── alloy-primitives v0.2.0 (https://github.com/alloy-rs/core?branch=main#3eab410e) │   ├── alloy-sol-types v0.2.0 (https://github.com/alloy-rs/core?branch=main#3eab410e) │   │   ├── alloy-primitives v0.2.0 (https://github.com/alloy-rs/core?branch=main#3eab410e) (*) │   │   ├── alloy-sol-macro v0.2.0 (proc-macro) (https://github.com/alloy-rs/core?branch=main#3eab410e) │   │   │   ├── syn-solidity v0.2.0 (https://github.com/alloy-rs/core?branch=main#3eab410e)

### Operating System

Linux

### Describe the bug

There are certain types of data that the `dyn-abi` decoder methods (`decode_params`, `decode_sequence`, `decode_single`) fail to decode correctly.

## Example 1

**Type:** `(string[],string[],string,uint24,address)`

**Data (as json):**

```json
[
  [
    "gNEwPzb\n",
    "d+`}C{$_",
    "Ji!SFg^f",
    "T{\\+{IU2",
    "Jk~jDY1\n",
    "\n~,WQf;o",
    "Ue::oRI#",
    "{ ']J.jJ"
  ],
  [
    "C*+zbWul",
    "oO,`t680",
    "V(];yDxR"
  ],
  "qYTCBn(E",
  13621740,
  "0x4f5dbfa6851957eab62570ec5a7a7304a7618c0d"
]
```

**Error (from `DynSolType::decode_params`):** `Type check failed for "Solidity pointer (uint32)" with data: 674e4577507a620a000000000000000000000000000000000000000000000000`

## Example 2

**Type:** `(bytes30,bytes31,address,bytes31,bytes32[2],uint112,bytes32,string[])`

**Data (as json):**

```json
[
  "0x9839ca7297d5df5a40d73482859778c00463365089ee823854d274010e93",
  "0xf7f77b3ea9176a6aeb0847c33716cae6567ea7b306405d0b9eb42e78f4ceea",
  "0x804e7f8acf6a8959d46265f779488aaff7f4ef2f",
  "0x6dcb308ae9e6360513d3673f12658cd44be1feec7b8b85a64efabd208587e8",
  [
    "0xea382a6123efaf1fc5c25a99ace015095f4050078b79dbffffd2c286fb672082",
    "0x40a20913c82de7725858dc1cc53c4b10c3561d072e58b4ed5f3f695e26d79324"
  ],
  1613240693945980444269411056144978,
  "0x27d627b4de4b75b83c6bbc12c633efc31593c4b10de2a2a4f77422e42e6fbe47",
  [
    "\r*&k4}.^pOR^x\n25O|\u000b#As#0LGqS;9IX`hlQX=%[}zwTt?DMZStcEl}Yq^^i$<tXh0D%]#z#8f7zB)salE<P\\>7H\\4[g\\A'N0:,H8\n$9B~[7\r)Y\n6Sg>L3#{\u000b5OP}9tv",
    "+Zd\u000beF\fWX)'1W?K\u000b>q",
    "'qI1m,!oO'21\tL#@\"`\rAg\t4|"
  ]
]
```

**Error (from `DynSolType::decode_params`):** `Type check failed for "Solidity pointer (uint32)" with data: 0000000000000000000000000000000000004f89f5d169e8bce841281b02d252`

## Example 3

**Type:** `(bytes22,(bytes9[],string)[],bytes,uint200,bytes13,address)`

**Data (as json):**

```json
[
  "0x6be25a61350829e7d21728e60c4af483b068f8697cbe",
  [
    [
      [
        "0x3d087033bc44049df8",
        "0x12188bfe07770c84d9"
      ],
      "%r6\"zWyj)XP_B?>._~/J.3!BNCKG^]A,+_X<f@8F\\t?qN\u000bvxl7>nR\u000boq5YNYAEN51kL$cSqP"
    ],
    [
      [
        "0x59df7607fcf965043e",
        "0x99d15c7fa5434787bd"
      ],
      "0g\tEJhQ g&1\fE4|q"
    ]
  ],
  "0xff26530d3839f2c9755525bbd557073e6cbbd29a862f3307cdd5952aa6e318280f45ad3d254747aaafdb51f1a38625477336ecc2771203e6952fe84b474b6ab46a9cbf81fd5f39",
  10252521428253414868099309238095001370685855238315029898719,
  "0x0d751e237aec5d0a891b06633f",
  "0x5824517a27e605ea65cb24c968c75556e7d9a9e2"
]
```

**Error (from `DynSolType::decode_params`):** `Buffer overrun while deserializing`

### PR DESCRIPTION
**Pull request by prestwich**
closes #167 

## Motivation

Branch was initially to add tests to dyn-abi. Uncovered a few bugs 

## Solution
- fix indirection in dyn sequence decoding
- fix offset propagation in `DynToken::FixedSeq` decoding
- fix `DynSolValue::tail_words` impl for fixed and dyn sequences
- improve code quality generally for sequences
- cool & useful display impl for `Decoder`
- feat: `DynSolValue::total_words`
- tests: start migrating them to dyn-abi
- fix: parsing of `(bool,)` single-element tuples in dyn sol type parser

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/dyn-abi/src/token.rs [hunk 1]
```diff
@@ -134,29 +134,31 @@ impl<'a> DynToken<'a> {
...
                     dec.take_indirection()?
                 } else {
                     dec.raw_child()
                 };
-                for token in tokens.to_mut().iter_mut().take(*size) {
-                    token.decode_populate(&mut child)?;
+
+                self.decode_sequence_populate(&mut child)?;
+
+                if !dynamic {
```
Comment (prestwich) [inline crates/dyn-abi/src/token.rs:146]: bug: missed offset propagation resulted in bad decoding

File: crates/dyn-abi/src/value.rs [hunk 2]
```diff
@@ -470,16 +470,23 @@ impl DynSolValue {
         }
 
         if let Some(vals) = self.as_fixed_seq() {
-            return self.is_dynamic() as usize * vals.len()
+            return self.is_dynamic() as usize * vals.iter().map(Self::total_words).sum::<usize>()
```
Comment (prestwich) [inline crates/dyn-abi/src/value.rs:473]: bug: incorrect tail words for fixed seqs

File: crates/dyn-abi/src/value.rs [hunk 3]
```diff
@@ -470,16 +470,23 @@ impl DynSolValue {
...
         }
 
         if let Some(vals) = self.as_array() {
-            return 1 + vals.iter().map(Self::tail_words).sum::<usize>()
+            // 1 for the length. Then all words for all elements.
+            return 1 + vals.iter().map(Self::total_words).sum::<usize>()
```
Comment (prestwich) [inline crates/dyn-abi/src/value.rs:478]: bug: incorrect tail words for dyn seqs

File: crates/dyn-abi/src/type.rs [hunk 4]
```diff
@@ -328,6 +328,29 @@ mod tests {
     use alloy_primitives::Address;
     use serde_json::json;
 
+    use hex_literal::hex;
+
+    macro_rules! encoder_test {
+        ($ty:literal, $encoded:ident) => {
```
Comment (DaniPopes) [inline crates/dyn-abi/src/type.rs:334]: drier if you want

```suggestion
        ($($name:ident($ty:literal, $encoded:literal)),* $(,)?) => {
```

make it expand to

```rust
#[test]
fn $name() {
    let encoded = hex!($encoded);
    ...
]
```

File: crates/sol-types/src/coder/decoder.rs [hunk 5]
```diff
@@ -31,14 +31,35 @@ pub struct Decoder<'de> {
...
     }
 }
 
+impl fmt::Display for Decoder<'_> {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        let mut body = self
+            .buf
+            .chunks(32)
+            .enumerate()
+            .map(|(i, chunk)| format!("0x{:0>4x}: {}", i * 32, hex::encode_prefixed(chunk)))
```
Comment (DaniPopes) [inline crates/sol-types/src/coder/decoder.rs:55]:
```suggestion
            .map(|(i, chunk)| format!("0x{:04x}: {}", i * 32, hex::encode_prefixed(chunk)))
```

File: crates/sol-types/src/coder/decoder.rs [hunk 6]
```diff
@@ -31,14 +31,35 @@ pub struct Decoder<'de> {
...
+            .collect::<Vec<_>>();
```
Comment (DaniPopes) [inline crates/sol-types/src/coder/decoder.rs:56]: we can write this in a for loop with `writeln!` instead of allocating if we cared

File: crates/sol-types/src/coder/decoder.rs [hunk 7]
```diff
@@ -31,14 +31,35 @@ pub struct Decoder<'de> {
...
+        body[self.offset / 32].push_str(" <-- Next Word");
+        writeln!(f, "\nAbi Decode Buffer")?;
```
Comment (DaniPopes) [inline crates/sol-types/src/coder/decoder.rs:58]:
```suggestion
        writeln!(f, "Abi Decode Buffer:")?;
```

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/dyn-abi/src/parser.rs [hunk 8]
```diff
@@ -202,7 +203,11 @@ impl<'a> TryFrom<&'a str> for TupleSpecifier<'a> {
                 _ => {}
             }
         }
-        types.push(value[start..].try_into()?);
+        // handle termina commas in tuples
+        let candidate = value[start..].trim();
```
Comment (prestwich) [inline crates/dyn-abi/src/parser.rs:207]: this was a bug. for `(T,)` it would include the blank string, which would fail parsing into a typespecifier

File: crates/dyn-abi/src/parser.rs [hunk 9]
```diff
@@ -202,7 +203,11 @@ impl<'a> TryFrom<&'a str> for TupleSpecifier<'a> {
                 _ => {}
             }
         }
-        types.push(value[start..].try_into()?);
+        // handle termina commas in tuples
```
Comment (DaniPopes) [inline crates/dyn-abi/src/parser.rs:206]:
```suggestion
        // handle trailing commas in tuples
```

File: crates/dyn-abi/src/parser.rs [hunk 10]
```diff
@@ -188,6 +188,7 @@ impl<'a> TryFrom<&'a str> for TupleSpecifier<'a> {
         let value = value.strip_prefix("tuple").unwrap_or(value);
         let value = value.strip_prefix('(').unwrap_or(value);
 
+        // passes over nested tuples
         let mut types = vec![];
         let mut start = 0;
         let mut depth = 0;
```
Comment (DaniPopes) [inline crates/dyn-abi/src/parser.rs:194]: can you explicitly make `depth` `i32` or `isize`, so it doesn't change in the future and cause unwanted overflows?

File: crates/dyn-abi/src/token.rs [hunk 11]
```diff
@@ -134,29 +134,35 @@ impl<'a> DynToken<'a> {
...
-                    new_tokens.push(t);
-                }
+                // This appears to be an unclarity in the solidity spec. The
+                // spec specifies that offsets are relative to the beginning of
+                // `enc(X)`. But known-good test vectors have it relative to the
+                // word AFTER the array size
+                let mut child = child.raw_child();
+
+                let mut new_tokens: Vec<_> = Vec::with_capacity(size);
+                new_tokens.resize(size, *(template.take().unwrap()));
```
Comment (DaniPopes) [inline crates/dyn-abi/src/token.rs:160]: this unwrap can panic, also unused parens

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/dyn-abi/src/token.rs (hunk 11 above)
Comment (prestwich) [reply crates/dyn-abi/src/token.rs:160]: if it panics, it's an implementation bug. I'll add an expect and a note why

the bug here is that the function should be pub(crate)

File: crates/dyn-abi/src/parser.rs (hunk 10 above)
Comment (prestwich) [reply crates/dyn-abi/src/parser.rs]: - making this explicitly usize
- handling underflows as mismatched paren errors
- handling mismatched parens more generally
- fixing a bug that allowed mismatched stripping of leading/trailing parents

File: crates/dyn-abi/src/parser.rs [hunk 12]
```diff
@@ -184,25 +184,49 @@ impl<'a> TryFrom<&'a str> for TupleSpecifier<'a> {
...
+                .ok_or_else(|| DynAbiError::invalid_type_string(value))?
+        } else {
+            value
+        };
+
+        let value = value
+            .strip_suffix(')')
+            .and_then(|val| val.strip_prefix('('))
+            .and_then(|val| val.strip_prefix("tuple"))
+            .unwrap_or(value);
```
Comment (DaniPopes) [inline crates/dyn-abi/src/parser.rs:202]: doesn't this strip twice? `((bool,), (bool,))` -> first `(bool,), (bool,)` -> second `bool,) bool,`

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/dyn-abi/src/parser.rs (hunk 12 above)
Comment (prestwich) [reply crates/dyn-abi/src/parser.rs:202]: oh lol i added the fixed code and forgot to remove the incorrect code

**Review by DaniPopes — APPROVED** [review]
Can you add a test case for parsing nested tuples? rest LGTM
