### PR TITLE
fix(`sol!`)!: gen unit struct for no param events

### LINKED ISSUE #879: [Feature] feat(`sol!`)!: improve event bindings
### Component

sol! macro

### Describe the feature you would like

```rust
sol! {
    contract Errors {
        event SomeEvent();
    }
}
```

Currently generated bindings:

```rust
struct SomeEvent {}
```

Proposed bindings, similar to what is proposed in #878 and #855 

```rust
// Unit struct NOT empty struct
struct SomeEvent;
```

Bindings for events with params remain unchanged.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #879 
Stacked over #883 

## Solution

- If event does not contain any params, generate a unit struct instead of an empty struct.

```rust
sol! {
   event Empty();
}

// New 
pub struct Empty;

// Previous 
pub struct Empty {};
```

Bindings for events with params remain unchanged.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/sol-macro-expander/src/expand/event.rs [hunk 1]
```diff
@@ -146,14 +146,24 @@ pub(super) fn expand(cx: &ExpCtxt<'_>, event: &ItemEvent) -> Result<TokenStream>
 
     let alloy_sol_types = &cx.crates.sol_types;
 
+    let event_struct = if event.parameters.is_empty() {
+        quote! {
+            pub struct #name;
```
Comment (mattsse) [inline crates/sol-macro-expander/src/expand/event.rs:151]: should we derive default in these cases?

**Review by mattsse — APPROVED** [review]

**Comment by DaniPopes** [comment]
I don't think we should do this, it doesn't make that much of a difference to keep it consistent when there are no fields vs 1 or more fields.

**Review by DaniPopes — APPROVED** [review]
