### PR TITLE
feat(primitives): fixed bytes macros

### LINKED ISSUE #109: [Feature] Add `FixedBytes` and aliases macros
### Component

_No response_

### Describe the feature you would like

Exported `macro_rules!` that wrap [`hex_literal::hex!`](https://docs.rs/hex-literal) with `$crate::<type>` constructors. Also re-export `hex!` itself

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Closes #109

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/primitives/src/bits/address.rs [hunk 1]
```diff
@@ -103,18 +102,41 @@ impl fmt::Display for Address {
...
+    ///     Address::from_word(word),
+    ///     address!("d8da6bf26964af9d7eed9e03e53415d37aa96045")
+    /// );
+    /// ```
     #[inline]
-    pub fn from_word(hash: FixedBytes<32>) -> Self {
-        Self(FixedBytes(hash[12..].try_into().unwrap()))
+    #[must_use]
+    pub fn from_word(word: FixedBytes<32>) -> Self {
+        Self(FixedBytes(word[12..].try_into().unwrap()))
```
Comment (prestwich) [inline crates/primitives/src/bits/address.rs:120]: Consider for a future PR:
should this error if the top bytes are dirty?

Comment (DaniPopes) [reply crates/primitives/src/bits/address.rs:120]: In another method maybe
