### PR TITLE
fix(sol-macro): bug fixes

### LINKED ISSUE #360: [Bug] single element tuples must have a trailing comma.
### Component

sol! macro

### What version of Alloy are you on?

_No response_

### Operating System

None

### Describe the bug

image
https://etherscan.io/address/0xef2ed07cc7a0825ced8ac1a67f88a0e17414fa6c#code

### LINKED ISSUE #361: [Bug] field `_1` on type `&PairCreated` and contructor type missmatch
### Component

sol! macro

### What version of Alloy are you on?

_No response_

### Operating System

None

### Describe the bug

image
https://etherscan.io/address/0xbf092d8f9d56d8b8ee063f48aa722dea52d650e4#code
https://etherscan.io/address/0x34cfac646f301356faa8b21e94227e3583fe3f5f#code

 expected reference `&'static str`
            found enum constructor `fn(Contract0x34cfac646f301356faa8b21e94227e3583fe3f5f::NAMECall) -> Contract0x34cfac646f301356faa8b21e94227e3583fe3f5fCalls {Contract0x34cfac646f301356faa8b21e94227e3583fe3f5fCalls::NAME}`

### LINKED ISSUE #369: [Bug] expected parentheses
### Component

sol! macro

### What version of Alloy are you on?

_No response_

### Operating System

Linux

### Describe the bug

image
https://etherscan.io/address/0x00000000000001ad428e4906ae43d8f9852d0dd6

### LINKED ISSUE #371: [Bug] infinite recusion on 0xC10DdeaCd46146a9Ca6E27467443383Ee080EfbC
### Component

sol! macro

### What version of Alloy are you on?

_No response_

### Operating System

None

### Describe the bug

image
pretty sure this is an error given its deployed on etherscan and builds without any errors

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Fixes #360
Fixes #361
Fixes #371

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/sol-macro/src/expand/contract.rs [hunk 1]
```diff
@@ -314,7 +314,7 @@ impl<'a> CallLikeExpander<'a> {
                                 .map(Self::#variants)
                         })*
                         s => ::core::result::Result::Err(::alloy_sol_types::Error::unknown_selector(
-                            Self::NAME,
+                            <Self as ::alloy_sol_types::SolInterface>::NAME,
```
Comment (DaniPopes) [inline crates/sol-macro/src/expand/contract.rs:317]: Part of 1 of issue #361
`expected reference &'static str found enum constructor`

File: crates/sol-macro/src/expand/mod.rs [hunk 2]
```diff
@@ -27,22 +28,22 @@ mod udt;
 mod var_def;
 
 /// The limit for the number of times to resolve a type.
-const RESOLVE_LIMIT: usize = 8;
+const RESOLVE_LIMIT: usize = 32;
```
Comment (DaniPopes) [inline crates/sol-macro/src/expand/mod.rs:31]: #371

File: crates/sol-macro/src/expand/mod.rs [hunk 3]
```diff
@@ -27,22 +28,22 @@ mod udt;
...
+/// The [`sol!`](crate::sol!) expansion implementation.
 pub fn expand(ast: File) -> Result<TokenStream> {
     ExpCtxt::new(&ast).expand()
 }
 
 /// The expansion context.
 struct ExpCtxt<'ast> {
     all_items: Vec<&'ast Item>,
-    custom_types: HashMap<SolIdent, Type>,
+    custom_types: IndexMap<SolIdent, Type>,
```
Comment (DaniPopes) [inline crates/sol-macro/src/expand/mod.rs:41]: `IndexMap` lets us have deterministic iteration and thus output (errors etc).

File: crates/sol-macro/src/expand/mod.rs [hunk 4]
```diff
@@ -597,3 +594,39 @@ fn expand_tuple_types<'a, I: IntoIterator<Item = &'a Type>>(
...
+    )
+}
+
+/// Expand the body of a `tokenize` function.
+fn expand_event_tokenize<'a>(params: impl IntoIterator<Item = &'a EventParameter>) -> TokenStream {
+    tokenize_(
+        params
+            .into_iter()
+            .enumerate()
+            .filter(|(_, p)| !p.is_indexed())
```
Comment (DaniPopes) [inline crates/sol-macro/src/expand/mod.rs:614]: #361 - enumerate before filter

File: crates/json-abi/src/to_sol.rs [hunk 5]
```diff
@@ -399,6 +399,10 @@ fn param<'a>(
                     out,
                 );
             }
+            // trailing comma for single-element tuples
+            if components.len() == 1 {
+                out.push(',');
+            }
```
Comment (DaniPopes) [inline crates/json-abi/src/to_sol.rs:405]: #360
