### PR TITLE
fix bincode serialization

### LINKED ISSUE #221: [Bug] `bincode` deserialization fails for fixed-size byte arrays
### Component

primitives

### What version of Alloy are you on?

alloy-primitives v0.3.1

### Operating System

None

### Describe the bug

Trying to use `bincode` to deserialize `FixedBytes<N>` fails because `deserializer.deserialize_any` is not supported.

Code snippet to reproduce this bug:
```rust
let hash = B256::ZERO;
bincode::deserialize::<B256>(&bincode::serialize(&hash).unwrap()).unwrap();
```

The `serde` documentation also discourages the use of `deserialize_any` for this very reason:
> When implementing Deserialize, you should avoid relying on Deserializer::deserialize_any unless you need to be told by the Deserializer what type is in the input. Know that relying on Deserializer::deserialize_any means your data type will be able to deserialize from self-describing formats only, ruling out Postcard and many others.

However, as I understand #202, JSON deserialization support for either a byte array, byte sequence, or string was explicitly required. Here I see a possible compromise to also check `is_human_readable()` in the deserialization and keep the current parsing only for human readable, e.g. JSON, and use `deserializer.deserialize_bytes` otherwise, which would also allow `bincode` and similar formats.

If this approach is acceptable, I would be happy to provide a PR.

### PR DESCRIPTION
**Pull request by Wollac**
## Motivation

Fixes `bincode` deserialization of `FixedBytes` and `Bytes`.

## Solution

Distinguish between `is_human_readable` and not also in the deserialization. If it is not human readable (e.g. `bincode`) allow only bytes instead of also strings.
This fixes #221 .

Added tests for the `bincode` roundtrip that previously failed.

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/primitives/src/bits/serde.rs [hunk 1]
```diff
@@ -18,58 +18,82 @@ impl<const N: usize> Serialize for FixedBytes<N> {
 
 impl<'de, const N: usize> Deserialize<'de> for FixedBytes<N> {
     fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
-        struct FixedVisitor<const N: usize>;
+        if deserializer.is_human_readable() {
```
Comment (prestwich) [inline crates/primitives/src/bits/serde.rs:21]: couldn't this be simplified to avoid the second visitor definition?

```
if deserializer.is_human_readable() {
    deserializer.deserialize_any(FixedVisitor::<N>)
} else {
    deserializer.deserialize_bytes(FixedVisitor::<N>)
```

Comment (Wollac) [reply crates/primitives/src/bits/serde.rs:21]: Very good point. I'll doublecheck to see if anything weird happens with those then unused methods, but I don't suspect it.

Comment (Wollac) [reply crates/primitives/src/bits/serde.rs]: changed

File: crates/primitives/src/bytes/serde.rs [hunk 2]
```diff
@@ -53,13 +53,18 @@ impl<'de> serde::Deserialize<'de> for Bytes {
...
+        } else {
+            deserializer.deserialize_byte_buf(BytesVisitor)
+        }
     }
 }
 
 #[cfg(test)]
 mod tests {
     use super::*;
+    use bincode as _;
```
Comment (DaniPopes) [inline crates/primitives/src/bytes/serde.rs:67]: Nit: I don't think this does anything

```suggestion
```

**Review by DaniPopes — CHANGES_REQUESTED** [review]
LGTM after nit and rebase to fix clippy

File: crates/primitives/src/bytes/serde.rs (hunk 2 above)
Comment (Wollac) [reply crates/primitives/src/bytes/serde.rs:67]: Without those I got:
```
warning: external crate `bincode` unused in `alloy_primitives`: remove the dependency or add `use bincode as _;`
```
When building the tests without the `serde` feature.
I don't know how to prevent this warning. Is there a better way?

Comment (DaniPopes) [reply crates/primitives/src/bytes/serde.rs]: Ah I see, it's fine then. The problem is that it gets included in the test binaries but not in the library, so it flags it as unused in the library.

Comment (Wollac) [reply crates/primitives/src/bytes/serde.rs]: So we decided to have the `use` in? In both places?
What I don't really understand is why the same is not needed for `serde_json`. Seems like it's only used in the serde tests as well...

Comment (DaniPopes) [reply crates/primitives/src/bytes/serde.rs:67]: It is: https://github.com/alloy-rs/core/blob/4f7a72c476de6b008be275daaa577ef9e89156e5/crates/primitives/src/lib.rs#L20-L24

**Review by DaniPopes — APPROVED** [review]
Thanks!
